### ISSUE TITLE
Unrecognized configuration parameter

### ISSUE THREAD

**Issue by rodo** [dimitri/preprepare#3]
**custom_variable_classes** not available on pg9.3, I have this error when trying to restart the cluster : 

    LOG:  unrecognized configuration parameter "custom_variable_classes" in file "/etc/postgresql/9.3/main/postgresql.conf" line 597
    FATAL:  configuration file "/etc/postgresql/9.3/main/postgresql.conf" contains errors

My postgresql.conf file

```
   592  #------------------------------------------------------------------------------
   593  # CUSTOMIZED OPTIONS
   594  #------------------------------------------------------------------------------
   595
   596  # Add settings for extensions here
   597  custom_variable_classes = 'preprepare'
   598  preprepare.at_init  = on
   599  preprepare.relation = 'preprepare.statements'
```

**Comment by schemaczar** [comment]
Yah, so what do we do if we need some variable on every session?

**Comment by dimitri** [comment]
Just omit the `custom_variable_classes` line.

**Comment by dimitri** [comment]
Thanks @ChristophBerg !
